### Задача №1

Найти ближайшую ортогональную матрицу (в смысле нормы
Фробениуса) к матрице:

$$ A = \begin{pmatrix} 0.5 &  2.16506351 & 0.4330127\\\ −0.8660254 & 1.25 & 0.25 \\\ 0 & 0.5 & 2.5 \end{pmatrix} $$

Посмотрев на результат, найти соответствующие этому преобразованию угол и
направление поворота. Матрицу, угол и направление поворота распечатать в
stdout.

$$ \argmin\|A-B\|$$

$$где \enspace B^TB=E, \enspace тогда $$

$$ A = UDV^T $$

$$ B=UV^T $$

In [17]:
import numpy as np
np.set_printoptions(precision=2)

A = np.matrix([[0.5, 2.16506351, 0.4330127],
                [-0.8660254, 1.25, 0.25],
                [0, 0.5, 2.5]])
U, D, V_T = np.linalg.svd(A, full_matrices=True, compute_uv=True, hermitian=False)
U, D, V_T

(matrix([[ 6.12e-01,  6.12e-01, -5.00e-01],
         [ 3.54e-01,  3.54e-01,  8.66e-01],
         [ 7.07e-01, -7.07e-01, -7.29e-10]]),
 array([3., 2., 1.]),
 matrix([[ 4.42e-10,  7.07e-01,  7.07e-01],
         [ 1.18e-09,  7.07e-01, -7.07e-01],
         [-1.00e+00,  1.15e-09, -5.21e-10]]))

In [18]:
B = np.dot(U, V_T)
print(f"Ближайшая ортоганальная матрица:\n{B}")

Ближайшая ортоганальная матрица:
[[ 5.00e-01  8.66e-01 -3.88e-10]
 [-8.66e-01  5.00e-01  1.66e-11]
 [ 2.08e-10  3.28e-10  1.00e+00]]


Сделаем небольшую проверку:

In [19]:
np.dot(B.T, B)

matrix([[ 1.00e+00, -1.13e-17, -4.64e-17],
        [-1.13e-17,  1.00e+00,  7.23e-17],
        [-4.64e-17,  7.23e-17,  1.00e+00]])

Как видим, произведение транспонированной матирцы на саму себя дает единичную матрицу.

In [20]:
np.linalg.det(B)

1.0000000000000004

Как и полагалось, определитель матрицы поворота равен единице.

Найденная матрица соответствует виду:

$$ \begin{pmatrix} \cos\phi &  -\sin\phi & 0\\\
 \sin\phi & \cos\phi & 0 \\\
  0 & 0 & 1 \end{pmatrix} $$

  Что свидетельствует о том, что мы имеем дело с поворотом вокруг оси z против часовой стрелки на угол $300^o$.

### Задача №2

При помощи SVD найти обратную матрицу к квадратной матрице nxn,
состоящей из элементов

$$ A_{ij} = \frac{1}{i+j-1}$$

для размеров матрицы n=3 и n=10. Результат распечатать в stdout.


In [21]:
n=3
A_3 = np.matrix([[1/(i+j-1) for j in range(1, n+1)] for i in range(1, n+1)])
A_3

matrix([[1.  , 0.5 , 0.33],
        [0.5 , 0.33, 0.25],
        [0.33, 0.25, 0.2 ]])

In [22]:
A_3_inv = np.linalg.pinv(A_3)
print(f"Обратная матрица:\n{A_3_inv}")

Обратная матрица:
[[   9.  -36.   30.]
 [ -36.  192. -180.]
 [  30. -180.  180.]]


In [23]:
n=10
A_10 = np.matrix([[1/(i+j-1) for j in range(1, n+1)] for i in range(1, n+1)])
A_10

matrix([[1.  , 0.5 , 0.33, 0.25, 0.2 , 0.17, 0.14, 0.12, 0.11, 0.1 ],
        [0.5 , 0.33, 0.25, 0.2 , 0.17, 0.14, 0.12, 0.11, 0.1 , 0.09],
        [0.33, 0.25, 0.2 , 0.17, 0.14, 0.12, 0.11, 0.1 , 0.09, 0.08],
        [0.25, 0.2 , 0.17, 0.14, 0.12, 0.11, 0.1 , 0.09, 0.08, 0.08],
        [0.2 , 0.17, 0.14, 0.12, 0.11, 0.1 , 0.09, 0.08, 0.08, 0.07],
        [0.17, 0.14, 0.12, 0.11, 0.1 , 0.09, 0.08, 0.08, 0.07, 0.07],
        [0.14, 0.12, 0.11, 0.1 , 0.09, 0.08, 0.08, 0.07, 0.07, 0.06],
        [0.12, 0.11, 0.1 , 0.09, 0.08, 0.08, 0.07, 0.07, 0.06, 0.06],
        [0.11, 0.1 , 0.09, 0.08, 0.08, 0.07, 0.07, 0.06, 0.06, 0.06],
        [0.1 , 0.09, 0.08, 0.08, 0.07, 0.07, 0.06, 0.06, 0.06, 0.05]])

In [24]:
A_10_inv = np.linalg.pinv(A_10)
print(f"Обратная матрица:\n{A_10_inv}")

Обратная матрица:
[[ 1.00e+02 -4.95e+03  7.92e+04 -6.01e+05  2.52e+06 -6.31e+06  9.61e+06
  -8.75e+06  4.38e+06 -9.24e+05]
 [-4.95e+03  3.27e+05 -5.88e+06  4.76e+07 -2.08e+08  5.35e+08 -8.32e+08
   7.70e+08 -3.90e+08  8.31e+07]
 [ 7.92e+04 -5.88e+06  1.13e+08 -9.51e+08  4.28e+09 -1.12e+10  1.78e+10
  -1.66e+10  8.51e+09 -1.83e+09]
 [-6.01e+05  4.76e+07 -9.51e+08  8.24e+09 -3.79e+10  1.01e+11 -1.62e+11
   1.53e+11 -7.88e+10  1.71e+10]
 [ 2.52e+06 -2.08e+08  4.28e+09 -3.79e+10  1.77e+11 -4.77e+11  7.71e+11
  -7.36e+11  3.82e+11 -8.32e+10]
 [-6.31e+06  5.35e+08 -1.12e+10  1.01e+11 -4.77e+11  1.30e+12 -2.12e+12
   2.04e+12 -1.06e+12  2.33e+11]
 [ 9.61e+06 -8.32e+08  1.78e+10 -1.62e+11  7.71e+11 -2.12e+12  3.48e+12
  -3.36e+12  1.77e+12 -3.88e+11]
 [-8.75e+06  7.70e+08 -1.66e+10  1.53e+11 -7.36e+11  2.04e+12 -3.36e+12
   3.27e+12 -1.72e+12  3.80e+11]
 [ 4.38e+06 -3.90e+08  8.51e+09 -7.88e+10  3.82e+11 -1.06e+12  1.77e+12
  -1.72e+12  9.12e+11 -2.02e+11]
 [-9.24e+05  8.31e+07 -1.83e+09  1.71

### Задача №3

Для квадратной матрицы nxn, состоящей из элементов

$$ A_{ij} = i+j-1$$

найти с использованием SVD все решения уравнений $AX=0$ для n=4 Результат
распечатать в stdout.

$$ Если \enspace A = UDV^T $$

$$ тогда \enspace X = V*diag(1/s_{ii})*U^T*B$$

In [25]:
n=4
A_4 = np.matrix([[i+j-1 for j in range(1, n+1)] for i in range(1, n+1)])
A_4

matrix([[1, 2, 3, 4],
        [2, 3, 4, 5],
        [3, 4, 5, 6],
        [4, 5, 6, 7]])

In [26]:
B = np.zeros((4, 1))
B

array([[0.],
       [0.],
       [0.],
       [0.]])

In [27]:
U, D, V_T = np.linalg.svd(A_4, full_matrices=True, compute_uv=True, hermitian=False)
U, D, V_T

(matrix([[-0.31, -0.78,  0.55,  0.04],
         [-0.43, -0.34, -0.75,  0.36],
         [-0.54,  0.09, -0.13, -0.83],
         [-0.65,  0.52,  0.34,  0.43]]),
 array([1.72e+01, 1.17e+00, 1.11e-15, 4.76e-17]),
 matrix([[-0.31, -0.43, -0.54, -0.65],
         [ 0.78,  0.34, -0.09, -0.52],
         [ 0.38, -0.22, -0.71,  0.55],
         [ 0.39, -0.81,  0.44, -0.02]]))

In [28]:
D_1 = np.diagflat(1/D)
D_1

array([[5.83e-02, 0.00e+00, 0.00e+00, 0.00e+00],
       [0.00e+00, 8.58e-01, 0.00e+00, 0.00e+00],
       [0.00e+00, 0.00e+00, 9.01e+14, 0.00e+00],
       [0.00e+00, 0.00e+00, 0.00e+00, 2.10e+16]])

In [29]:
X = V_T.T.dot(D_1).dot(U.T).dot(B)
print(f"Получили тривиальное решение:\n{X}")

Получили тривиальное решение:
[[0.]
 [0.]
 [0.]
 [0.]]


In [32]:
a = np.where(np.isclose(D, 0))[0]
solutions = V_T.T[:, a]
solutions

matrix([[ 0.38,  0.39],
        [-0.22, -0.81],
        [-0.71,  0.44],
        [ 0.55, -0.02]])

### Задача №4

 Написать программу, находящую все точки пересечения двух прямых на
плоскости методом однородных координат. Прямые заданы уравнениями ax+by+c
= 0, cx+dy+e=0. Коэффициенты задать константами на ваше усмотрение. Результат
распечатать в stdout.


In [ ]:
a, b, c = 4, 2, 3
c, d, e = 3, 6, 5

x, y, z = b*e-d*c, c*c-a*e, a*d-c*b
x/z, y/z, z/z

(-0.4444444444444444, -0.6111111111111112, 1.0)